package scsai.cmb.datasource.inf;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import scsai.cmb.datasource.entity.BusnessOrder;
import scsai.cmb.datasource.entity.BusnessOrderExample;

public interface BusnessOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	long countByExample(BusnessOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int deleteByExample(BusnessOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int insert(BusnessOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int insertSelective(BusnessOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	List<BusnessOrder> selectByExample(BusnessOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	BusnessOrder selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") BusnessOrder record, @Param("example") BusnessOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") BusnessOrder record, @Param("example") BusnessOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(BusnessOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BUSNESS_ORDER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByPrimaryKey(BusnessOrder record);
}