package scsai.cmb.datasource.inf;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import scsai.cmb.datasource.entity.RequestInfo;
import scsai.cmb.datasource.entity.RequestInfoExample;

public interface RequestInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	long countByExample(RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int deleteByExample(RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int insert(RequestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int insertSelective(RequestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	List<RequestInfo> selectByExample(RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	RequestInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") RequestInfo record, @Param("example") RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") RequestInfo record, @Param("example") RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(RequestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	int updateByPrimaryKey(RequestInfo record);

	int updateByPk4Response(Date date);
}