package scsai.cmb.datasource.entity;

public class BookType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column booktypes.id
	 * @mbg.generated  Sun Apr 02 01:47:30 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column booktypes.typeName
	 * @mbg.generated  Sun Apr 02 01:47:30 GMT+08:00 2017
	 */
	private String typename;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column booktypes.id
	 * @return  the value of booktypes.id
	 * @mbg.generated  Sun Apr 02 01:47:30 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column booktypes.id
	 * @param id  the value for booktypes.id
	 * @mbg.generated  Sun Apr 02 01:47:30 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column booktypes.typeName
	 * @return  the value of booktypes.typeName
	 * @mbg.generated  Sun Apr 02 01:47:30 GMT+08:00 2017
	 */
	public String getTypename() {
		return typename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column booktypes.typeName
	 * @param typename  the value for booktypes.typeName
	 * @mbg.generated  Sun Apr 02 01:47:30 GMT+08:00 2017
	 */
	public void setTypename(String typename) {
		this.typename = typename;
	}
}