package scsai.cmb.datasource.entity;

import java.util.Date;

public class BusnessOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.USER_ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.BUSNESS_ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Integer busnessId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.BUSNESS_NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String busnessName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.CREATE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.PRICE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.CREATE_TIME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ORDER.USER_NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String userName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.ID
	 * @return  the value of BUSNESS_ORDER.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.ID
	 * @param id  the value for BUSNESS_ORDER.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.USER_ID
	 * @return  the value of BUSNESS_ORDER.USER_ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.USER_ID
	 * @param userId  the value for BUSNESS_ORDER.USER_ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.BUSNESS_ID
	 * @return  the value of BUSNESS_ORDER.BUSNESS_ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Integer getBusnessId() {
		return busnessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.BUSNESS_ID
	 * @param busnessId  the value for BUSNESS_ORDER.BUSNESS_ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setBusnessId(Integer busnessId) {
		this.busnessId = busnessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.BUSNESS_NAME
	 * @return  the value of BUSNESS_ORDER.BUSNESS_NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getBusnessName() {
		return busnessName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.BUSNESS_NAME
	 * @param busnessName  the value for BUSNESS_ORDER.BUSNESS_NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setBusnessName(String busnessName) {
		this.busnessName = busnessName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.CREATE_DATE
	 * @return  the value of BUSNESS_ORDER.CREATE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.CREATE_DATE
	 * @param createDate  the value for BUSNESS_ORDER.CREATE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.PRICE
	 * @return  the value of BUSNESS_ORDER.PRICE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.PRICE
	 * @param price  the value for BUSNESS_ORDER.PRICE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.CREATE_TIME
	 * @return  the value of BUSNESS_ORDER.CREATE_TIME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.CREATE_TIME
	 * @param createTime  the value for BUSNESS_ORDER.CREATE_TIME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ORDER.USER_NAME
	 * @return  the value of BUSNESS_ORDER.USER_NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ORDER.USER_NAME
	 * @param userName  the value for BUSNESS_ORDER.USER_NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
}