package scsai.cmb.datasource.entity;

public class BusnessItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ITEM.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ITEM.NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ITEM.PRICE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BUSNESS_ITEM.TOTAL_NUM
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Integer totalNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ITEM.ID
	 * @return  the value of BUSNESS_ITEM.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ITEM.ID
	 * @param id  the value for BUSNESS_ITEM.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ITEM.NAME
	 * @return  the value of BUSNESS_ITEM.NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ITEM.NAME
	 * @param name  the value for BUSNESS_ITEM.NAME
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ITEM.PRICE
	 * @return  the value of BUSNESS_ITEM.PRICE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ITEM.PRICE
	 * @param price  the value for BUSNESS_ITEM.PRICE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BUSNESS_ITEM.TOTAL_NUM
	 * @return  the value of BUSNESS_ITEM.TOTAL_NUM
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Integer getTotalNum() {
		return totalNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BUSNESS_ITEM.TOTAL_NUM
	 * @param totalNum  the value for BUSNESS_ITEM.TOTAL_NUM
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}
}