package scsai.cmb.datasource.entity;

import java.util.Date;

public class Custom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.ID
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.SEX
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.NAME
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.CARD_TYPE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private String cardType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.PHONE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.CARD_NUMB
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private String cardNumb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.ADDRESS
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.CREATE_DATE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CUSTOM.OP_DATE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	private Date opDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.ID
	 * @return  the value of CUSTOM.ID
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.ID
	 * @param id  the value for CUSTOM.ID
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.SEX
	 * @return  the value of CUSTOM.SEX
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.SEX
	 * @param sex  the value for CUSTOM.SEX
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.NAME
	 * @return  the value of CUSTOM.NAME
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.NAME
	 * @param name  the value for CUSTOM.NAME
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.CARD_TYPE
	 * @return  the value of CUSTOM.CARD_TYPE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public String getCardType() {
		return cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.CARD_TYPE
	 * @param cardType  the value for CUSTOM.CARD_TYPE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.PHONE
	 * @return  the value of CUSTOM.PHONE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.PHONE
	 * @param phone  the value for CUSTOM.PHONE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.CARD_NUMB
	 * @return  the value of CUSTOM.CARD_NUMB
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public String getCardNumb() {
		return cardNumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.CARD_NUMB
	 * @param cardNumb  the value for CUSTOM.CARD_NUMB
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setCardNumb(String cardNumb) {
		this.cardNumb = cardNumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.ADDRESS
	 * @return  the value of CUSTOM.ADDRESS
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.ADDRESS
	 * @param address  the value for CUSTOM.ADDRESS
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.CREATE_DATE
	 * @return  the value of CUSTOM.CREATE_DATE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.CREATE_DATE
	 * @param createDate  the value for CUSTOM.CREATE_DATE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CUSTOM.OP_DATE
	 * @return  the value of CUSTOM.OP_DATE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public Date getOpDate() {
		return opDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CUSTOM.OP_DATE
	 * @param opDate  the value for CUSTOM.OP_DATE
	 * @mbg.generated  Sun Apr 02 23:28:26 GMT+08:00 2017
	 */
	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

	@Override
	public String toString() {
		return "Custom [id=" + id + ", sex=" + sex + ", name=" + name + ", cardType=" + cardType + ", phone=" + phone
				+ ", cardNumb=" + cardNumb + ", address=" + address + ", createDate=" + createDate + ", opDate="
				+ opDate + "]";
	}
	
	
}