package scsai.cmb.datasource.entity;

import java.util.Date;

public class RequestInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.IP
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.CONTENT_LENGTH
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Integer contentLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.CONTENT_TYPE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.LOCAL_ADDR
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String localAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.REQUEST_PATH
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String requestPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.REQUEST_SERVER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String requestServer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.REQUEST_METHOD
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String requestMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.PROTOCOL
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String protocol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.QUERY
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String query;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.CREATE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.RESPONSE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Date responseDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUEST_INFO.IS_WORK
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Boolean isWork;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.ID
	 * @return  the value of REQUEST_INFO.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.ID
	 * @param id  the value for REQUEST_INFO.ID
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.IP
	 * @return  the value of REQUEST_INFO.IP
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.IP
	 * @param ip  the value for REQUEST_INFO.IP
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.CONTENT_LENGTH
	 * @return  the value of REQUEST_INFO.CONTENT_LENGTH
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Integer getContentLength() {
		return contentLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.CONTENT_LENGTH
	 * @param contentLength  the value for REQUEST_INFO.CONTENT_LENGTH
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setContentLength(Integer contentLength) {
		this.contentLength = contentLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.CONTENT_TYPE
	 * @return  the value of REQUEST_INFO.CONTENT_TYPE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.CONTENT_TYPE
	 * @param contentType  the value for REQUEST_INFO.CONTENT_TYPE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.LOCAL_ADDR
	 * @return  the value of REQUEST_INFO.LOCAL_ADDR
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getLocalAddr() {
		return localAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.LOCAL_ADDR
	 * @param localAddr  the value for REQUEST_INFO.LOCAL_ADDR
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setLocalAddr(String localAddr) {
		this.localAddr = localAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.REQUEST_PATH
	 * @return  the value of REQUEST_INFO.REQUEST_PATH
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getRequestPath() {
		return requestPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.REQUEST_PATH
	 * @param requestPath  the value for REQUEST_INFO.REQUEST_PATH
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setRequestPath(String requestPath) {
		this.requestPath = requestPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.REQUEST_SERVER
	 * @return  the value of REQUEST_INFO.REQUEST_SERVER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getRequestServer() {
		return requestServer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.REQUEST_SERVER
	 * @param requestServer  the value for REQUEST_INFO.REQUEST_SERVER
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setRequestServer(String requestServer) {
		this.requestServer = requestServer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.REQUEST_METHOD
	 * @return  the value of REQUEST_INFO.REQUEST_METHOD
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getRequestMethod() {
		return requestMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.REQUEST_METHOD
	 * @param requestMethod  the value for REQUEST_INFO.REQUEST_METHOD
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setRequestMethod(String requestMethod) {
		this.requestMethod = requestMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.PROTOCOL
	 * @return  the value of REQUEST_INFO.PROTOCOL
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getProtocol() {
		return protocol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.PROTOCOL
	 * @param protocol  the value for REQUEST_INFO.PROTOCOL
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setProtocol(String protocol) {
		this.protocol = protocol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.QUERY
	 * @return  the value of REQUEST_INFO.QUERY
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getQuery() {
		return query;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.QUERY
	 * @param query  the value for REQUEST_INFO.QUERY
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setQuery(String query) {
		this.query = query;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.CREATE_DATE
	 * @return  the value of REQUEST_INFO.CREATE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.CREATE_DATE
	 * @param createDate  the value for REQUEST_INFO.CREATE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.RESPONSE_DATE
	 * @return  the value of REQUEST_INFO.RESPONSE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Date getResponseDate() {
		return responseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.RESPONSE_DATE
	 * @param responseDate  the value for REQUEST_INFO.RESPONSE_DATE
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setResponseDate(Date responseDate) {
		this.responseDate = responseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUEST_INFO.IS_WORK
	 * @return  the value of REQUEST_INFO.IS_WORK
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Boolean getIsWork() {
		return isWork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUEST_INFO.IS_WORK
	 * @param isWork  the value for REQUEST_INFO.IS_WORK
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setIsWork(Boolean isWork) {
		this.isWork = isWork;
	}
}