package scsai.cmb.datasource.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column langcom.uid
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column langcom.pwd
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column langcom.username
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column langcom.cash
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	private Long cash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column langcom.uid
	 * @return  the value of langcom.uid
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column langcom.uid
	 * @param uid  the value for langcom.uid
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column langcom.pwd
	 * @return  the value of langcom.pwd
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column langcom.pwd
	 * @param pwd  the value for langcom.pwd
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column langcom.username
	 * @return  the value of langcom.username
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column langcom.username
	 * @param username  the value for langcom.username
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column langcom.cash
	 * @return  the value of langcom.cash
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public Long getCash() {
		return cash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column langcom.cash
	 * @param cash  the value for langcom.cash
	 * @mbg.generated  Wed May 17 01:48:54 GMT+08:00 2017
	 */
	public void setCash(Long cash) {
		this.cash = cash;
	}
}